dist: trusty
sudo: required
language: node_js
node_js:
  - "8.12.0"
cache: npm
before_script:
  - npm install -g truffle ganache-cli
script:
  - CI=false ganache-cli &
  - CI=false truffle test
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls